{"errorMessage": "A path prefix must start with '/'", "errorType": "AssertionError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n", "  File \"/var/task/main.py\", line 4, in <module>\n    from app.routes import users, habits, upload\n", "  File \"/var/task/app/routes/habits.py\", line 10, in <module>\n    router = APIRouter(prefix=\"habits\", tags=[\"Habits\"])\n", "  File \"/var/task/fastapi/routing.py\", line 846, in __init__\n    assert prefix.startswith(\"/\"), \"A path prefix must start with '/'\"\n"]}